import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";
import { Suspense } from "react";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});

const monaco = localFont({
  src: "../public/fonts/monaco-webfont.woff2",
  variable: "--font-monaco",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "title",
    description: "description",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      {/* <body className={inter.className}> */}
      {/* <body className={roboto.className}> */}
      <body className={monaco.variable}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
          {/* <main className="p-5">
              <Suspense fallback={<p>Loading...</p>}>{children}</Suspense>
            </main> */}
        </AuthProvider>
      </body>
    </html>
  );
}
